# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "puppetlabs/ubuntu-14.04-64-nocm"

  config.vm.provision "shell", inline: <<-SHELL
    sudo echo "LC_ALL=en_US.UTF-8" >> /etc/default/locale
    sudo export LC_ALL=en_US.UTF-8

    sudo wget -O /tmp/puppetlabs.deb http://apt.puppetlabs.com/puppetlabs-release-`lsb_release -cs`.deb
    sudo dpkg -i /tmp/puppetlabs.deb
    sudo apt-get update
    sudo apt-get -y install git-core puppet

    cd /etc
    sudo mv puppet/ puppet_bak
    git clone https://github.com/mmuehlberger/tutsplus-configuration-management /etc/puppet
    cd /etc/puppet
    git checkout puppet

    sudo puppet apply /etc/puppet/manifests/site.pp
  SHELL
end
