# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-14.04"

  config.vm.define :db do |db|
    db.vm.hostname = "db"
  end

  config.vm.define :web do |web|
    web.vm.hostname = "web"
  end
end
